apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* #skaffold will apply all config files on startup
build:
  local:
    push: false #disable default behaviour
  artifacts: #images to rebuild when changes occur
    - image: brandednomad/blog-client
      context: blog # tells skaffold that their is a pod running  code out of this folder in file directory, and to rebuild images if something changes inside of this directory and update the pod
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js' #if js file changes skaffold will attempt to copy it into the running pod without rebuilding an image
            dest: .
    - image: brandednomad/blog-service-comments
      context: comments # tells skaffold that their is a pod running  code out of this folder in file directory, and to rebuild images if something changes inside of this directory and update the pod
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js' #if js file changes skaffold will attempt to copy it into the running pod without rebuilding an image
            dest: .
    - image: brandednomad/blog-service-eventbus
      context: event-bus # tells skaffold that their is a pod running  code out of this folder in file directory, and to rebuild images if something changes inside of this directory and update the pod
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js' #if js file changes skaffold will attempt to copy it into the running pod without rebuilding an image
            dest: .
    - image: brandednomad/blog-service-moderation
      context: moderation # tells skaffold that their is a pod running  code out of this folder in file directory, and to rebuild images if something changes inside of this directory and update the pod
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js' #if js file changes skaffold will attempt to copy it into the running pod without rebuilding an image
            dest: .
    - image: brandednomad/blog-service-posts
      context: posts # tells skaffold that their is a pod running  code out of this folder in file directory, and to rebuild images if something changes inside of this directory and update the pod
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js' #if js file changes skaffold will attempt to copy it into the running pod without rebuilding an image
            dest: .
    - image: brandednomad/blog-service-query
      context: query # tells skaffold that their is a pod running  code out of this folder in file directory, and to rebuild images if something changes inside of this directory and update the pod
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js' #if js file changes skaffold will attempt to copy it into the running pod without rebuilding an image
            dest: .



