apiVersion: apps/v1 #deployment object is inside apps
kind: Deployment #kind of configuration
metadata:
  name: client-depl #name of deployment
spec:
  replicas: 1
  selector: # take a look at all the pods created
    matchLabels: #find all the pods with the following labels
      app: client #label name
  template: # specifies the configuration of pods to be created
    metadata:
      labels: # give the pod the following label
        app: client
    spec:
      containers: # run the following containers inside the pod
        - name: client
          image: brandednomad/blog-client
---
# ipcluster
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000 #port for create-react-app client
      targetPort: 3000
