apiVersion: apps/v1 #deployment object is inside apps
kind: Deployment #kind of configuration
metadata:
  name: moderation-depl #name of deployment
spec:
  replicas: 1
  selector: # take a look at all the pods created
    matchLabels: #find all the pods with the following labels
      app: moderation #label name
  template: # specifies the configuration of pods to be created
    metadata:
      labels: # give the pod the following label
        app: moderation
    spec:
      containers: # run the following containers inside the pod
        - name: moderation
          image: brandednomad/blog-service-moderation
---
# ipcluster
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  type: ClusterIP
  ports:
    - name: moderation
      protocol: TCP
      port: 3004
      targetPort: 3004
